[TOC]
###3 模块化
	Don’t interrupt me while I’m interrupting.	– Winston S. Churchill
    • 简介
    • 单独编译
    • 模块
    • 命名空间
    • 错误处理
        异常;不变量;错误处理方案;合同;静态断言
    • 函数参数和返回值
        参数传递;返回值;结构化绑定
    • 建议

####3.1 介绍
	c++程序由许多独立开发的部分组成，例如函数(§1.2.1)、用户定义的类型(第2章)、类层次结构(第4.5章)和模板(第6章)。管理这些部分的关键是清楚地定义这些部分之间的交互。第一步也是最重要的一步是区分部件的接口及其实现。在语言层面，c++通过声明来表示接口。声明指定了使用函数或类型所需的所有内容。例如:
        double sqrt(double); // the square root function takes a double and returns a double
        class Vector {
        public:
            Vector(int s);
            double& operator[](int i);
            int size();
        private:
            double∗ elem; // elem points to an array of sz doubles
            int sz;
        };
    这里的重点是，函数体和函数定义在“在别的地方”。对于这个例子，我们可能也希望Vector的表示形式为“在别的地方”，但我们将在后面处理(抽象类型;§4.3)。sqrt()的定义如下:
        double sqrt(double d) // definition of sqrt()
        {
         	// ... algorithm as found in math textbook ...
        }
    对于Vector，我们需要定义所有三个成员函数:
        Vector::Vector(int s) // definition of the constructor
        :elem{new double[s]}, sz{s} // initialize members
        {
        }
        double& Vector::operator[](int i) // definition of subscripting
        {
        	return elem[i];
        }
        int Vector::size() // definition of size()
        {
        	return sz;
        }
    必须定义Vector函数，但不能定义sqrt()，因为它是标准库的一部分。然而，这并没有真正的区别:库只是“我们碰巧使用的一些其他代码”，用我们使用的相同的语言工具编写的。
		一个实体可以有很多声明，比如函数，但只有一个定义。

####3.2 单独的编译
	c++支持单独编译的概念，用户代码只能看到所使用的类型和函数的声明。这些类型和函数的定义位于单独的源文件中，并分别编译。这可以用来将程序组织成一组半独立的代码片段。这种分离可用于最小化编译时间，并严格执行程序中逻辑上不同的部分的分离(从而最大限度地减少错误的机会)。库通常是一个单独编译的代码片段的集合(例如，函数)。
    	通常，我们将指定模块接口的声明放在一个文件中，该文件的名称表明其预期用途。例如:
        	// Vector.h:
            class Vector {
            public:
                Vector(int s);
                double& operator[](int i);
                int size();
            private:
                double∗ elem; // elem points to an array of sz doubles
                int sz;
            };
	这个声明将放在Vector.h文件中。然后用户包含该文件，称为头文件，以访问该接口。例如:
    	// user.cpp:
        #include "Vector.h" // get Vector’s interface
        #include <cmath> // get the standard-librar y math function interface including sqrt()
        double sqrt_sum(Vector& v)
        {
            double sum = 0;
            for (int i=0; i!=v.siz e(); ++i)
                sum+=std::sqr t(v[i]); // sum of square roots
            return sum;
        }
	为了帮助编译器确保一致性，提供Vector实现的.cpp文件还将包含提供其接口的.h文件:
    	// Vector.cpp:
        #include "Vector.h" // get Vector’s interface
        Vector::Vector(int s)
        :elem{new double[s]}, sz{s} // initialize members
        {
        }
        double& Vector::operator[](int i)
        {
        	return elem[i];
        }
        int Vector::siz e()
        {
        	return sz;
        }
	user.cpp和Vector.cpp中的代码共享Vector.h中提供的Vector接口信息，但是这两个文件在其他方面是独立的，可以单独编译。
    严格地说，使用单独编译不是一个语言问题;问题在于如何最好地利用特定的语言实现。然而，它具有重要的现实意义。组织程序的最佳方法是将程序视为一组具有良好定义的依赖关系的模块，通过语言特性在逻辑上表示该模块性，然后通过文件在物理上利用该模块性进行有效的单独编译。
		一个由自己编译的.cpp文件(包括它#包含的h文件)被称为翻译单元。一个程序可以由数千个翻译单元组成。

####3.3 模块(C++20)
	#include的使用是一种非常古老的、容易出错的、而且相当昂贵的用部分组合程序的方式。如果你在101个翻译单元中使用#include header.h，那么header.h的文本将被编译器处理101次。如果在header2.h之前包含header1.h, header1.h中的声明和宏可能会影响header2.h中的代码的含义。如果你改为#include header2.h在header1.h之前，这可能会影响header1.h中的代码。显然，这并不理想，事实上，自1972年该机制首次引入C以来，它一直是成本和bug的主要来源。
    	我们终于可以用c++更好地表达物理模块了。这个语言特性，称为模块，还不是ISO c++，但它是ISO技术规范[ModulesTS]，并将成为c++ 20的一部分。实现正在使用中，所以我冒险在这里推荐它，尽管细节可能会发生变化，而且在生产代码中使用它可能需要数年时间。
	旧代码(在本例中使用#include的代码)可以“存活”很长一段时间，因为更新它的成本很高，耗时也很长。
    	考虑如何使用模块来表达§3.2中的Vector和sqrt_sum()示例:
			// file Vector.cpp:
            module; // this compilation will define a module
            // ... here we put stuff that Vector might need for its implementation ...
            export module Vector; // defining the module called "Vector"
            export class Vector {
            public:
                Vector(int s);
                double& operator[](int i);
                int size();
            private:
                double∗ elem; // elem points to an array of sz doubles
                int sz;
            };
            Vector::Vector(int s)
            :elem{new double[s]}, sz{s} // initialize members
            {
            }
            double& Vector::operator[](int i)
            {
            	return elem[i];
            }
            int Vector::size()
            {
            	return sz;
            }
            export int size(const Vector& v) { return v.size(); }
    这定义了一个名为Vector的模块，该模块导出Vector类、其所有成员函数和非成员函数size()。
    	我们使用这个模块的方式是在我们需要它的地方导入它。例如:
        	// file user.cpp:
            import Vector; // get Vector’s interface
            #include <cmath> // get the standard-librar y math function interface including sqrt()
            double sqrt_sum(Vector& v)
            {
                double sum = 0;
                for (int i=0; i!=v.siz e(); ++i)
                    sum+=std::sqr t(v[i]); // sum of square roots
                return sum;
            }
	我也可以导入标准库的数学函数，但我使用老式的#include只是为了说明可以混合使用新旧函数。这种混合对于逐步将旧代码从使用#include升级为import是必不可少的。
        头文件和模块之间的区别不仅仅是语法上的。
        • 一个模块只编译一次(而不是在使用它的每个翻译单元中)。
        • 两个模块可以在不改变其含义的情况下以任意顺序导入。
        • 如果你导入了一些东西到一个模块中，模块的用户不会隐式地获得你导入的东西的访问权(也不会被打扰):importort是不可传递的。
        	这对可维护性和编译时性能的影响可能是惊人的。

####3.4 命名空间
	除了函数(§1.3)、类(§2.3)和枚举(§2.5)之外，c++还提供了命名空间作为一种机制，来表示某些声明属于一起，并且它们的名称不应与其他名称冲突。例如，我可能想尝试自己的复数类型(§4.2.1，§14.4):
        namespace My_code {
            class complex
            {
                // ...
            };
            complex sqrt(complex);
            // ...
            int main();
        }
        int My_code::main()
        {
            complex z {1,2};
            auto z2 = sqrt(z);
            std::cout << '{' << z2.real() << ',' << z2.imag() << "}\n";
            // ...
        }
        int main()
        {
        	return My_code::main();
        }
	通过将我的代码放入命名空间My_code中，我确保我的名称不会与命名空间std中的标准库名称冲突(§3.4)。这种谨慎是明智的，因为标准库确实提供了对复杂算术的支持(§4.2.1，§14.4)。
		访问另一个名称空间中的名称最简单的方法是用名称空间名称限定它(例如，std::cout和My_code::main)。“real main()”是在全局命名空间中定义的，也就是说，不是定义的命名空间、类或函数的局部名称空间。
		如果重复限定一个名称变得乏味或分散注意力，我们可以使用using-声明将该名称引入作用域:
        void my_code(vector<int>& x, vector<int>& y)
        {
            using std::swap; // use the standard-librar y sw ap
            // ...
            swap(x,y); // std::swap()
            other::swap(x,y); // some other swap()
            // ...
        }
	using-声明使名称空间中的名称可用，就好像它是在出现的作用域中声明的一样。在使用std::swap之后，就像在my_code()中声明了swap一样。
		要获得对标准库命名空间中所有名称的访问权，可以使用using-directive:
        using namespace std;
    using-directive使得命名空间中的非限定名可以从我们放置指令的作用域中访问。所以在std的using指令之后，我们可以简单地写cout而不是std::cout。通过使用using-directive，我们就失去了选择性地使用来自该名称空间的名称的能力，因此应该谨慎地使用该功能，通常用于应用程序中普遍存在的库(例如std)，或者用于不使用名称空间的应用程序的转换期间。
    	命名空间主要用于组织更大的程序组件，比如库。他们把独立开发的部分简化成一个程序。

####3.5 错误处理
	错误处理是一个庞大而复杂的主题，它所关注的问题和影响远远超出了语言工具，延伸到了编程技术和工具。但是，c++提供了一些功能来提供帮助。主要的工具是类型系统本身。我们不必费力地从内置类型(如char、int和double)和语句(如if、while和for)构建应用程序，而是构建适合应用程序的类型(如string、map和regex)和算法(如sort()、find_if()和draw_all())。这样的高级结构简化了我们的编程，限制了我们出错的机会(例如，您不太可能尝试对对话框应用树遍历)，并增加了编译器捕捉错误的机会。大多数c++语言构造都致力于设计和实现优雅而高效的抽象(例如，使用它们的用户定义类型和算法)。这种抽象的一个影响是，可以检测到运行时错误的点与可以处理错误的点是分离的。随着程序的发展，特别是当库被广泛使用时，处理错误的标准就变得重要起来。在程序开发的早期阐明错误处理策略是一个好主意。
	// 译注：是的，开发人员应该肯定自己的Code，但是需要对外部输入保持怀疑。

#####3.5.1 异常
	再次考虑Vector的例子。当我们试图访问§2.3中超出vector范围的元素时，应该怎么做?
    	• Vector的编写者不知道在这种情况下用户想要做什么(通常，Vector的编写者甚至不知道Vector将在哪个程序中运行)。
        • Vector的用户不能始终检测到问题(如果用户可以，超出范围的访问就不会发生在第一个地方)。
    假设超出范围的访问是我们想要恢复的一种错误，解决方案是由Vector实现者检测尝试的超出范围的访问，并告诉用户它。
	然后，用户可以采取适当的操作。例如，Vector::operator[]()可以检测到一个试图超出范围的访问，并抛出一个out_of_range异常:
        double& Vector::operator[](int i)
        {
            if (i<0 || size()<=i)
                throw out_of_range{"Vector::operator[]"};
            return elem[i];
        }
    throw将控制传递给某个函数中out_of_range类型异常的处理程序，该函数直接或间接调用Vector::operator[]()。为此，实现将根据需要展开函数调用堆栈，以返回调用者的上下文。也就是说，异常处理机制将根据需要退出作用域和函数，返回到表示有兴趣处理此类异常的调用者那里，并在需要的时候调用析构函数(§4.2.2)。
	例如:
        void f(Vector& v)
        {
            // ...
            try
            { / / exceptions here are handled by the handler defined below
                v[v.size()] = 7; // try to access beyond the end of v
            }
            catch (out_of_rang e& err)
            { // oops: out_of_range error
                // ... handle range error ...
                cerr << err.what() << '\n';
            }
            // ...
        }
    我们将对处理异常感兴趣的代码放入一个try块中。试图分配给v[v.size()]将失败。因此，将输入为out_of_range类型异常提供处理程序的catch子句。out_of_range类型在标准库中定义(在<stdexept>中)，实际上被一些标准库容器访问函数使用。
    	我通过引用捕获了异常，以避免复制，并使用what()函数打印抛出点处放入其中的错误消息。
    	使用异常处理机制可以使错误处理更简单、更系统、更可读。要实现这一点，不要过度使用try语句。使错误处理简单和系统的主要技术(称为资源获取是初始化;§4.2.2对此有解释。RAII背后的基本思想是，构造函数获取类操作所需的所有资源，并让析构函数释放所有资源，从而使资源释放具有保证性和隐式。
		一个不应该抛出异常的函数可以声明为noexcept。例如:
        void user(int sz) noexcept
        {
            Vector v(sz);
            iota(&v[0],&v[sz],1); // fill v with 1,2,3,4... (see §14.3)
            // ...
        }
    如果所有正常的意图和计划都失败了，因此user()仍然会抛出问题，则调用std::terminate()来立即终止程序。

#####3.5.2 不变量
	使用异常来表示超出范围的访问是一个例子，函数检查它的参数并拒绝行动，因为一个基本的假设、前提条件不成立。如果我们正式地指定Vector的下标操作符，我们就会说“索引必须在[0:size())范围内”，这实际上就是我们在操作符[]()中测试的内容。[a:b)表示法指定半开放范围，这意味着a是范围的一部分，但b不是。当我们定义一个函数时，我们必须考虑它的前提条件是什么，并考虑是否要检验这些前提条件(§3.5.3)。对于大多数应用程序来说，测试简单的不变量是个好主意;参见§3.5.4。
    	然而，operator[]()作用于Vector类型的对象，除非Vector的成员具有“合理”的值，否则没有任何意义。特别地，我们确实说过“elem指向一个sz双精度数组”，但我们只是在一个注释中说过。对于一个类来说，这样一个被假定为正确的陈述被称为类不变量，或者简单地称为不变量。构造函数的职责是为其类建立不变式(以便成员函数可以依赖于它)，成员函数的职责是确保在退出时保持不变式。不幸的是，Vector构造函数只完成了部分工作。它正确地初始化了Vector成员，但未能检查传递给它的参数是否合理。考虑:
			Vector v(−27);
    这很可能会引起混乱。
		这里有一个更合适的定义:
        Vector::Vector(int s)
        {
            if (s<0)
                throw length_error{"Vector constructor: negative size"};
            elem = new double[s];
            sz = s;
        }
    我使用标准库异常length_error来报告非正数的元素，因为一些标准库操作使用该异常来报告此类问题。如果操作符new找不到要分配的内存，它就会抛出一个std::bad_alloc。我们现在可以这样写:
            void test()
            {
                try
                {
                Vector v(−27);
            	}
                catch (std::length_error& err)
                {
                    // handle negative size
                }
                catch (std::bad_alloc& err)
                {
                    // handle memory exhaustion
                }
            }
    你可以定义自己的类作为异常使用，并让它们携带从检测到可以处理错误的任意信息(§3.5.1)。
    	通常，在抛出异常后，函数无法完成分配给它的任务。
		然后，“处理”异常意味着做一些最小的局部清理并重新抛出异常。例如:
            void test()
            {
                try
                {
                    Vector v(−27);
                }
                catch (std::length_error&)
                { // do something and rethrow
                    cerr << "test failed: length error\n";
                    throw; // rethrow
                }
                catch (std::bad_alloc&)
                { // Ouch! this program is not designed to handle memory exhaustion
                    std::terminate(); // ter minate the program
                }
            }
    在设计良好的代码中，try块很少出现。通过系统地使用RAII技术避免过度使用(§4.2.2，§5.3)。
    	不变量的概念是类设计的核心，前提条件在函数设计中也扮演着类似的角色。不变量
        • 帮助我们准确地理解我们想要什么
		• 迫使我们具体化;这为我们(在调试和测试之后)获得正确代码提供了更好的机会。
    不变量的概念是c++资源管理概念的基础，构造函数(第4章)和析构函数(§4.2.2和§13.2)都支持这种概念。

#####3.5.3 错误处理选项
	错误处理是所有现实软件中的一个主要问题，因此自然有各种各样的方法。如果检测到错误，并且无法在函数中本地处理它，那么函数必须以某种方式将问题传达给某些调用者。抛出异常是c++最常用的处理机制。
    	在某些语言中，异常的设计只是为了提供返回值的替代机制。c++不是这样一种语言:异常被设计用来报告未能完成给定任务。异常与构造函数和析构函数集成，为错误处理和资源管理提供了一个一致的框架(§4.2.2，§5.3)。编译器经过优化，返回一个值比抛出相同的值作为异常要便宜得多。
		抛出异常并不是报告无法在本地处理的错误的唯一方法。
	函数可以通过以下方式表示它不能执行分配的任务:
    	• 抛出异常
        • 以某种方式返回指示失败的值
        • 终止程序(通过调用terminate()、exit()或abor t()等函数)。
    我们返回一个错误指示器(一个“错误代码”)：
    	• 失败是正常的，也是意料之中的。例如，打开一个文件的请求失败是很正常的(可能没有该名称的文件，或者可能文件无法以所请求的权限打开)。
		• 可以合理地期望立即调用者来处理故障。
    我们抛出一个异常：
        • 一个错误是如此罕见，以至于程序员可能会忘记检查它。例如，上次检查printf()的返回值是什么时候?
        • 一个错误不能被直接调用者处理。相反，错误必须渗透回最终调用者。例如，让应用程序中的每个功能都可靠地处理每次分配失败或网络中断是不可行的。
        • 新的错误类型可以添加到应用程序的低级别模块中，这样就不会编写高级模块来处理此类错误。例如，当将以前的单线程应用程序修改为使用多个线程或将资源远程放置以便通过网络访问时。
        • 错误码没有合适的返回路径。例如，构造函数没有返回值供“调用者”检查。特别是，可能会为多个局部变量或部分构造的复杂对象调用构造函数，因此基于错误代码的清理将会非常复杂。
        • 函数的返回路径变得更加复杂或昂贵，因为它需要返回一个值和一个错误指示器(例如，一对;§13.4.3)，可能导致使用外部参数、非本地错误状态指示器或其他变通方法。
        • 错误必须通过调用链向上传输到“最终调用方”。“反复检查错误代码将是乏味、昂贵且容易出错的。
        • 从错误中恢复依赖于多个函数调用的结果，导致需要在调用和复杂的控制结构之间维护局部状态。
        • 发现错误的函数是回调函数(函数参数)，因此直接调用者甚至可能不知道被调用的是什么函数。
        • 一个错误意味着需要一些“撤消操作”。
    我们终止
    	• 错误是一种我们无法挽回的错误。例如，对于许多(但不是所有)系统，没有合理的方法从内存耗尽中恢复。
        • 该系统的错误处理是基于每当检测到重大错误时重新启动线程、进程或计算机。
    确保终止的一种方法是向函数中添加noexcept，这样函数实现中任何地方的throw都将变成terminate()。请注意，有些应用程序不能接受无条件终止，因此必须使用替代方案。
    	不幸的是，这些条件在逻辑上并不总是不相关的，并且很容易应用。程序的大小和复杂性很重要。有时，随着应用程序的发展，权衡也会发生变化。
    经验是必需的。当有疑问时，首选异常，因为它们的使用伸缩性更好，并且不需要外部工具来检查所有错误是否得到处理。
    	不要认为所有的错误代码或异常都是坏的;两者都有明确的用途。此外，不要相信异常处理是缓慢的神话;这通常比正确处理复杂或罕见的错误条件和重复测试错误代码要快。
		RAII(§4.2.2，§5.3)对于使用异常进行简单而有效的错误处理至关重要。充斥着try块的代码通常只是反映了为错误代码设计的错误处理策略的最糟糕的方面。

#####3.5.4 约定
	目前还没有通用和标准的方法来编写不变量、前提条件等的可选运行时测试。为c++ 20 [Garcia,2016] [Garcia,2018]提出了一个契约机制。其目的是支持那些希望依靠测试来获得正确程序的用户——使用大量的运行时检查来运行程序——但随后使用最少的检查来部署代码。这在依赖于系统和广泛检查的组织中的高性能应用程序中很流行。
    	就目前而言，我们必须依靠专门的机制。例如，我们可以使用命令行宏来控制运行时检查:
		double& Vector::operator[](int i)
        {
            if (RANGE_CHECK && (i<0 || size()<=i))
                throw out_of_rang e{"Vector::operator[]"};
            return elem[i];
        }
    标准库提供了调试宏assert()来断言一个条件必须在运行时保持。例如:
    	void f(const char∗ p)
        {
            asser t(p!=nullptr); // p must not be the nullptr
            // ...
        }
    如果assert()的条件在“调试模式”中失败，程序将终止。如果我们没有处于调试模式，则不会检查assert()。这是相当粗糙和不灵活的，但通常足够了。

#####3.5.5 静态断言
	异常报告运行时发现的错误。如果可以在编译时找到错误，那么最好这样做。这就是大部分类型系统和为用户定义类型指定接口的工具的用途。但是，我们也可以对大部分属性执行简单的检查，这些属性在编译时已知，并报告不符合我们预期的编译器错误消息。例如:
    	static_assert(4<=sizeof(int), "integers are too small"); // check integer size
    如果4<=sizeof(int)不成立，将写入整数太小;也就是说，如果这个系统上的int没有至少4个字节。我们称这样的期望声明为断言。
		static_assert机制可以用于任何可以用常量表达式表示的东西(§1.6)。例如:
        constexpr double C = 299792.458; // km/s
        void f(double speed)
        {
            constexpr double local_max = 160.0/(60∗60); // 160 km/h == 160.0/(60*60) km/s
            static_assert(speed<C,"can't go that fast"); // error : speed must be a constant
            static_assert(local_max<C,"can't go that fast"); // OK
            // ...
        }
    通常，如果A不为真，static_assert(A,S)会打印S作为编译器错误消息。如果你不想打印一个特定的消息，省略S，编译器将提供一个默认消息:
    	static_asser t(4<=sizeof(int)); // use default message
    默认消息通常是static_assert的源位置加上断言谓词的字符表示。
    	当我们在泛型编程中断言作为参数使用的类型时，static_asser最重要的用途就出现了(§7.2，§13.9)。

####3.6 函数参数和返回值
	将信息从程序的一个部分传递到另一个部分的主要方法是通过函数调用。执行任务所需的信息作为参数传递给函数，产生的结果作为返回值传递回来。例如:
    	int sum(const vector<int>& v)
        {
            int s = 0;
            for (const int i : v)
            	s + = i ;
            return s;
        }
        vector fib = {1,2,3,5,8,13,21};
        int x = sum(fib); // x becomes 53
	函数之间还可以通过其他途径传递信息，比如全局变量(§1.5)、指针和引用形参(§3.6.1)以及类对象中的共享状态(第4章)。强烈反对将全局变量作为已知的错误来源，状态通常只应该在共同实现定义良好的抽象的函数之间共享(例如，类的成员函数;§2.3)。
    	考虑到在函数之间传递信息的重要性，有各种不同的方式来传递信息也就不足为奇了。关键担心的是:
        • 对象是复制的还是共享的?
        • 如果一个对象是共享的，它是可变的吗?
        • 一个对象移动了，留下了一个“空对象”(§5.2.2)?
    参数传递和返回值的默认行为都是“copy”(§1.9)，但有些copy可以隐式地优化为move。
    	在sum()的例子中，得到的int是从sum()中复制出来的，但将可能非常大的向量复制到sum()中效率低下且毫无意义，因此参数通过引用传递(由&;§1.7)。
        sum()没有理由修改它的参数。这种不可变性通过声明vector实参const(§1.6)来表示，因此vector对象通过const引用传递。

#####3.6.1参数传递
	首先考虑如何将值输入函数。默认情况下，复制(“按值传递”)，如果要引用调用者环境中的对象，则使用引用(“按值传递”)。
	例如:
        void test(vector<int> v, vector<int>& rv) // v is passed by value; rv is passed by reference
        {
            v[1] = 99; // modify v (a local var iable)
            rv[2] = 66; // modify whatever rv refers to
        }
        int main()
        {
            vector fib = {1,2,3,5,8,13,21};
            test(fib,fib);
            cout << fib[1] << ' ' << fib[2] << '\n'; // prints 2 66
        }
    当我们关心性能时，我们通常是按值传递小值，按引用传递大值。在这里，“small”指的是“很容易复制的东西”。“小”的确切含义取决于机器架构，但“两三个指针或更少的大小”是一个很好的经验法则。
    	如果出于性能考虑，需要按引用传递参数，但又不需要修改参数，则可以像sum()示例中那样按const-reference传递参数。到目前为止，这是普通优秀代码中最常见的情况:它快速且不容易出错。
        函数实参有一个默认值是很常见的;也就是说，该值被认为是首选值或最常见的值。可以通过默认函数实参指定这样的默认值。例如:
        void print(int value , int base =10); // print value in base "base"
        print(x,16); // hexadecimal
        print(x,60); // sexagesimal (Sumerian)
        print(x); // use the dafault: decimal
    这是一种符号上更简单的重载替代方法:
    	void print(int value , int base); // print value in base "base"
        void print(int value) // print value in base 10
        {
        	print(value ,10);
        }

#####3.6.2 返回值
	一旦我们计算出一个结果，我们需要将它从函数中取出并返回给调用者。同样，返回值的默认值是复制，对于小对象来说这是理想的。只有当我们想要授予调用者访问非函数本地内容的权限时，才返回“通过引用”。例如:
        class Vector {
        public:
            // ...
            double& operator[](int i) { return elem[i]; } // retur n reference to ith element
        private:
            double∗ elem; // elem points to an array of sz
            // ...
        };
    Vector对象的第i个元素独立于下标操作符的调用而存在，因此可以返回对它的引用。
    	另一方面，局部变量在函数返回时消失，所以我们不应该返回指向它的指针或引用:
        int& bad()
        {
            int x;
            // ...
            return x; // bad: return a reference to the local var iable x
        }
    幸运的是，所有主要的c++编译器都会捕捉bad()中的明显错误。
    	返回引用或“小”类型的值是有效的，但是我们如何从函数中传递大量的信息呢?考虑:
        Matrix operator+(const Matrix& x, const Matrix& y)
        {
            Matrix res;
            // ... for all res[i,j], res[i,j] = x[i,j]+y[i,j] ...
            return res;
        }
        Matrix m1, m2;
        // ...
        Matrix m3 = m1+m2; // no copy
    即使在现代硬件上，矩阵也可能非常大，而且复制成本很高。所以我们不复制，而是给Matrix一个转移构造函数(§5.2.2)，并很容易地将Matrix从操作符+()中移出。不需要退回到使用手动内存管理:
    	Matrix∗ add(const Matrix& x, const Matrix& y) // complicated and error-prone 20th century style
        {
            Matrix∗ p = new Matrix;
            // ... for all *p[i,j], *p[i,j] = x[i,j]+y[i,j] ...
            return p;
        }
        Matrix m1, m2;
        // ...
        Matrix∗ m3 = add(m1,m2); // just copy a pointer
        // ...
        delete m3; // easily forgotten
    不幸的是，通过返回指向大对象的指针返回大对象在旧代码中很常见，这也是很难找到错误的主要来源。不要编写这样的代码。注意，operator+()与add()一样有效，但是更容易定义、更容易使用、更不容易出错。
    	如果一个函数不能执行它所要求的任务，它可以抛出异常(§3.5.1)。这可以帮助避免代码被“异常问题”的错误代码测试弄得一团糟。
        函数的返回类型可以从它的返回值推断出来。例如:
        auto mul(int i, double d) { return i∗d; } // here, "auto" means "deduce the return type"
    这很方便，特别是对于泛型函数(函数模板;(§6.3.1)和lambdas(§6.3.3)，但是应该谨慎使用，因为推导的类型不能提供稳定的接口:对函数(或lambda)实现的更改可能会改变类型。

#####3.6.3 结构化绑定
	函数只能返回一个值，但这个值可以是一个具有多个成员的类对象。
	这允许我们高效地返回许多值。例如:
        struct Entry {
            string name;
            int value;
        };
        Entry read_entry(istream& is) // naive read function (for a better version, see §10.5)
        {
            string s;
            int i;
            is >> s >> i;
            return {s,i};
        }
        auto e = read_entry(cin);
		cout << "{ " << e.name << " , " << e.value << " }\n";
    这里，{s,i}被用来构造entry y的返回值。类似地，我们可以将entry y的成员“解包”到局部变量中:
        auto [n,v] = read_entry(is);
        cout << "{ " << n << " , " << v << " }\n";
    auto [n,v]声明了两个局部变量n和v，它们的类型从read_entry y()的返回类型推导而来。这种为类对象的成员指定局部名称的机制称为结构化绑定。
    	考虑另一个例子:
        	map<string,int> m;
            // ... fill m ...
            for (const auto [key,value] : m)
            	cout << "{" << key "," << value << "}\n";
    和往常一样，我们可以用const和&来装饰auto。例如:
        void incr(map<string,int>& m) // increment the value of each element of m
        {
            for (auto& [key,value] : m)
            	++value;
        }
    当对没有私有数据的类使用结构化绑定时，很容易看到绑定是如何完成的:为绑定定义的名称数量必须与类的非静态数据成员的数量相同，绑定中引入的每个名称都是对应的成员。
	与显式使用复合对象相比，目标代码的质量不会有任何区别;结构化绑定的使用完全是关于如何最好地表达一个想法。
    	还可以处理通过成员函数访问的类。例如:
        complex<double> z = {1,2};
		auto [re,im] = z+2; // re=3; im=2
    complex函数有两个数据成员，但是它的接口由访问函数组成，比如real()和imag()。将复杂的映射到两个局部变量(如re和im)是可行且有效的，但是这样做的技术超出了本书的范围。

####3.7 建议
    [1] 区分声明(用作接口)和定义(用作实现);§3.1。
    [2] 使用头文件表示接口，强调逻辑结构;§3.2;[CG: SF.3]。
    [3] 在源文件中包含实现其函数的头文件;§3.2;[CG: SF.5]。
    [4] 避免在头文件中定义非内联函数;§3.2;[CG: SF.2]。
    [5] 优先选择模块而不是头文件(支持模块);§3.3。
    [6] 使用名称空间表达逻辑结构;§3.4;[CG: SF.20]。
    [7] 在转换、基础库(如std)或局部作用域内使用using-directive;§3.4;[cg: sf.6] [cg: sf.7]
    [8] 不要在头文件中放入using-directive;§3.4;[CG: SF.7]。
    [9] 抛出异常，表示无法执行分配的任务;§3.5;[CG: E.2]。
    [10] 仅将异常用于错误处理;§3.5.3;[CG: E.3]。
    [11] 当期望立即调用者处理错误时使用错误代码;§3.5.3。
    [12] 如果预期错误将通过多个函数调用向上渗透，则抛出异常;§3.5.3。
    [13] 如果不确定是使用异常还是错误代码，首选exceptions;§3.5.3。
    [14] 在设计早期制定错误处理策略;§3.5;[CG: E.12]。
    [15] 使用专门设计的用户定义类型作为异常(不是内置类型);§3.5.1。
    [16] 不要试图捕捉每个函数中的每个异常;§3.5;[CG: E.7]。
    [17] 宁愿选择RAII而不是显式的try -blocks;§3.5.1,§3.5.2;[CG: E.6]。
    [18] 如果你的函数不抛出，声明它noexcept;§3.5;[CG: E.12]。
    [19] 让构造函数建立一个不变式，如果不能，则抛出;§3.5.2;[CG: E.5]。
    [20] 围绕不变量设计错误处理策略;§3.5.2;[CG: E.4]。
    [21] 在编译时可以检查的通常最好在编译时检查;§3.5.5 [cg: p .4] [cg: p .5]
    [22] 通过值传递“小”值，通过引用传递“大”值;§3.6.1;[CG: F.16]。
    [23] 优先选择通过const-reference传递而不是普通的通过引用传递;§3.6.1;[CG: F.17]。
    [24] 返回值作为函数返回值(而不是通过输出参数);§操作;[cg: f.20] [cg: f.21]。
    [26] 不要过度使用返回类型的扣除;§操作。
    [27] 不要过度使用结构化绑定;使用命名返回类型通常更清晰的文档;§3.6.3。

[Next](study/computer/notebooks/A-Tour-of-C++/4.md)